name: Weather report
on:
  schedule:
    - cron: "16 * * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  weather:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        city: ["Mumbai", "Bejing", "London", "Prague"]
    steps:
      - name: Fetch weather
        run: |
          CITY="${{ matrix.city }}"
          WEATHER=$(curl -s "wttr.in/$CITY?format=3")
          echo "Current weather in $CITY: $WEATHER"
          
          # Put the file in a city-specific folder to avoid conflicts
          mkdir -p output
          echo "Weather in $CITY: $WEATHER" > output/${CITY}.txt

      - name: Upload Unique Artifact
        uses: actions/upload-artifact@v4
        with:
          # This name MUST be unique per matrix row
          name: report-${{ matrix.city }}
          path: output/