name: Weather report
on:
  schedule:
    - cron: "57 * * * *"
  push:
    branches: [main]
  workflow_dispatch:

# Add permissions so the bot can deploy to Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  weather:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        city: ["Mumbai", "Bejing", "London", "Prague"]
    steps:
      - name: Fetch weather
        run: |
          CITY="${{ matrix.city }}"
          WEATHER=$(curl -s "wttr.in/$CITY?format=3")
          # Create a folder for our website files
          mkdir -p public
          echo "<h1>Weather for $CITY</h1><p>$WEATHER</p>" > public/${CITY}.html

      - name: Upload for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: weather # Wait for all 4 cities to finish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4